package com.TTN.AmazonWebsite.EnumOrderStatus;

public enum Fromstatus {
    CANCELLED,
    DELIVERED,
    ORDER_CONFIRMED,
    ORDER_REJEJCTED,
    ORDER_SHIPPED,
    OREDER_PLACED,
    PICK_UP_COMPLETED,
    PICK_UP_INITIATED,
    REFUND_COMPLETED,
    REFUND_INITIATED,
    RETURN_APPROVED,
    RETURN_REQUESTED

}
